package com.returnradar.enums;

public enum IssueType {
    MISSING_INSPECTION,
    DUPLICATE_RETURN,
    INVALID_REFUND_AMOUNT,
    INCONSISTENT_WAREHOUSE_RECORD,
    MISSING_ORDER_REFERENCE,
    SUSPICIOUS_RETURN_PATTERN
}
